// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAll() {
  return window['go']['main']['DesktopApp']['CheckAll']();
}

export function ExportGoodProxies() {
  return window['go']['main']['DesktopApp']['ExportGoodProxies']();
}

export function GetState() {
  return window['go']['main']['DesktopApp']['GetState']();
}

export function GetVersion() {
  return window['go']['main']['DesktopApp']['GetVersion']();
}

export function LoadFilePath(arg1) {
  return window['go']['main']['DesktopApp']['LoadFilePath'](arg1);
}

export function LoadURL(arg1) {
  return window['go']['main']['DesktopApp']['LoadURL'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['DesktopApp']['SaveSettings'](arg1);
}

export function SelectProxyFile() {
  return window['go']['main']['DesktopApp']['SelectProxyFile']();
}

export function StartMonitor() {
  return window['go']['main']['DesktopApp']['StartMonitor']();
}

export function StartThreeProxy() {
  return window['go']['main']['DesktopApp']['StartThreeProxy']();
}

export function StopMonitor() {
  return window['go']['main']['DesktopApp']['StopMonitor']();
}

export function StopThreeProxy() {
  return window['go']['main']['DesktopApp']['StopThreeProxy']();
}
