// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckAll():Promise<main.apiResponse>;

export function ExportGoodProxies():Promise<main.apiResponse>;

export function GetState():Promise<main.StateSnapshot>;

export function GetVersion():Promise<Record<string, any>>;

export function LoadFilePath(arg1:string):Promise<main.apiResponse>;

export function LoadURL(arg1:string):Promise<main.apiResponse>;

export function RemoveDeadProxies():Promise<main.apiResponse>;

export function SaveSettings(arg1:main.AppConfig):Promise<main.apiResponse>;

export function SelectProxyFile():Promise<string>;

export function StartMonitor():Promise<main.apiResponse>;

export function StartThreeProxy():Promise<main.apiResponse>;

export function StopMonitor():Promise<main.apiResponse>;

export function StopThreeProxy():Promise<main.apiResponse>;
